config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/eddiesGNN:
      branch: main
      repo: https://github.com/HPCI-Lab/eddiesGNN
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/eddiesGNN git:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-auburn-kingfisher.sh
        container: qc.acc_snazzy-gold-sponge
  QC.Doc:
    repos:
      github.com/HPCI-Lab/eddiesGNN find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-cornflower-cichlid.sh
        container: qc.doc_pretty-platinum-impala
      github.com/HPCI-Lab/eddiesGNN git:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-auburn-zonkey.sh
        container: qc.doc_wimpy-razzmatazz-stingray
  QC.Lic:
    repos:
      github.com/HPCI-Lab/eddiesGNN licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-aquamarine-rattlesnake.sh
        container: qc.lic_trippy-jade-ostrich
  QC.Ver:
    repos:
      github.com/HPCI-Lab/eddiesGNN get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-ochre-cockroach.sh
        container: qc.ver_sunny-razzmatazz-centipede
timeout: 5400
